language: groovy
jdk:
  - oraclejdk8
install: echo "skip 'gradle assemble' step"
script: ./gradlew build --continue
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.m2/
